Replace os.mkdir() with recursive directory creation function
Like mkdir(), but makes all intermediate-level directories needed to contain the
leaf directory.

This is fix for Cygwin bug:
```
przwir01@E104178 /usr/bin
$ mbedls
Traceback (most recent call last):
  File "C:\Python27.11\Scripts\mbedls-script.py", line 9, in <module>
    load_entry_point('mbed-ls', 'console_scripts', 'mbedls')()
  File "c:\work\pypi\mbed-ls\mbed_lstools\main.py", line 163, in mbedls_main
    mbeds = create()
  File "c:\work\pypi\mbed-ls\mbed_lstools\main.py", line 42, in create
    if mbed_os == 'Windows7': result = MbedLsToolsWin7()
  File "c:\work\pypi\mbed-ls\mbed_lstools\lstools_win7.py", line 32, in __init__
    MbedLsToolsBase.__init__(self)
  File "c:\work\pypi\mbed-ls\mbed_lstools\lstools_base.py", line 39, in __init__
    self.mbedls_home_dir_init()
  File "c:\work\pypi\mbed-ls\mbed_lstools\lstools_base.py", line 212, in mbedls_                                                                               home_dir_init
    os.mkdir(os.path.join(self.HOME_DIR, self.MBEDLS_HOME_DIR))
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\cygwin\\                                                                               home\\przwir01\\.mbed-ls'
```